# Generated by Django 5.2.3 on 2025-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_category_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.RenameField(
            model_name="advertisement",
            old_name="author",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                help_text="Оцените объявление от 1 до 5",
                verbose_name="Оценка",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
    ]
