# Generated by Django 5.2.3 on 2025-06-29 18:32

from django.db import migrations, models

def validate_prices(apps, schema_editor):
    Advertisement = apps.get_model('board', 'Advertisement')
    for ad in Advertisement.objects.all():
        if ad.price <= 0:
            ad.price = 0.01
            ad.save()

class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
