# Generated by Django 5.2.3 on 2025-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_alter_advertisement_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
