# Generated by Django 5.2.3 on 2025-06-29 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_advertisement_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
