# Generated by Django 5.2.3 on 2025-06-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_advertisement_price_and_more"),
    ]

    operations = []
