# Generated by Django 5.2.3 on 2025-06-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_remove_advertisement_board_advertisement_price_check"),
    ]

    operations = []
