# Generated by Django 5.2.3 on 2025-06-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_fix_price_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="board.category",
            ),
        ),
    ]
