# Generated by Django 5.2.3 on 2025-07-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_alter_advertisement_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="ad",
            new_name="advertisement",
        ),
    ]
