# Generated by Django 5.2.3 on 2025-07-02 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0011_rename_ad_comment_advertisement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
