# Generated by Django 5.2.3 on 2025-07-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0012_alter_advertisement_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
